name: refri_g5_flutter
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  refri_g5:
    path: ../refri-g5

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/icon.png
    - assets/images/lata.png
    - assets/images/garrafa.png
    - assets/images/popup.png
  fonts:
    - family: Baloo2
      fonts:
        - asset: assets/fonts/baloo2/static/baloo2variable.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/montserratnormalvariable.ttf

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700